services:
  test:
    image: ubuntu-song:20.04
    command: /usr/sbin/sshd -D -e & && sleep infinity
    ports:
      - "3232:22"
    volumes:
      - type: bind
        source: /ssd1t/song/Datasets/
        target: /opt/data
        read_only: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0', '1']
            capabilities: [gpu]
